#
# docker build -t bex-libs-el7 .
# docker run -v $PWD:/app -it bex-libs-el7 /bin/bash
#
FROM centos:7.3.1611

RUN yum install -y http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum -y install ant \
                   autoconf \
                   binutils \
                   bison \
                   bzip2 \
                   bzip2-devel \
                   chrpath \
                   cmake \
                   cppunit \
                   curl-devel \
                   db4-devel \
                   expat-devel \
                   flex \
                   freetype-devel \
                   gcc \
                   gcc-c++ \
                   gcc-gfortran \
                   gdbm-devel \
                   git \
                   glibc-devel \
                   java-1.8.0-openjdk-devel \
                   krb5-devel \
                   libcurl-devel \
                   libgcj-devel \
                   libjpeg-devel \
                   libjpeg-turbo-devel \
                   libpng-devel \
                   libtiff-devel \
                   libtool \
                   libxml2-devel \
                   libxslt-devel \
                   make \
                   ncurses-devel \
                   openssl-devel \
                   pam-devel \
                   perl-devel \
                   pkgconfig \
                   poppler-devel \
                   readline-devel \
                   sqlite-devel \
                   tcl-devel \
                   tk-devel \
                   unzip \
                   wget \
                   xerces-c-devel \
                   zlib-devel
