#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "registry-creatdb requires root user access"
  exit
fi

source /etc/profile.d/vendor-libs.sh

/opt/registry/.venv/bin/python /opt/registry/registry.py pycsw -c setup_db
